### ISSUE TITLE
Some client issues/improvements

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/external-project#41]
I've been writing things down as I notice them. I'm just going to throw them in one issue instead of making a bunch. These are all related to the client/simple browser...

- [x] no inline code syntax highlighting
- [ ] extra dash in titles
- [x] test text get cut off on the right
- [ ] #43

**Comment by ShaunSHamilton** [comment]
I will leave the dash for you to decide on, because, the only reason it is there is to allow titles like:
<img width="330" alt="image" src="https://user-images.githubusercontent.com/51722130/165534086-63f83ccb-a900-4529-a453-498b367b1799.png">

---

Could you explain what sort of loader you imagine? As in, where and when does this show?

**Comment by moT01** [comment]
Not really sure on the loader, but when I run course, the simple browser opens with a white screen while everything installs - which can take a decent amount of time. I dunno, I would have to play with - could we somehow load a static index.html file with a css loader until the server starts? Then redirect to that or something. That's all that comes to mind at the moment.
